name: Feature Request
description: Request a new extension, feature or enhancement to existing extensions
title: "[Feature Request]: "
labels: [enhancement]
body:
  - type: dropdown
    attributes:
      label: Choose the extension for feature request.
      description: Choose other if not related to any extension mentioned in the dropdown.
      options:
          - 🎆 New Extension Idea
          - Save Playlists
          - Full Screen Mode
          - Auto Skip
          - Play Next
          - Volume Percentage
          - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 📝 Provide a description of the new feature
      description: What is the expected behavior of the proposed feature? What is the scenario this would be used?
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: ➕ Additional Information
      description: Give us some additional information on the feature request like proposed solutions, links, screenshots, etc.

  - type: markdown
    attributes:
      value: If you'd like to see this feature implemented, add a 👍 reaction to this post.
